config/routes.rb
Rails.application.routes.draw do
  require 'sidekiq/web'
  mount Sidekiq::Web => "/sidekiq"

  resources :whales
  post 'whales/report' => 'whales#report', as: :report

  root 'whales#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/install.rb
class Install < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/whale.rb
class Whale < ApplicationRecord
  def self.save
    Whale.create(name: "Will 2")
  end

  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/whales_controller.rb
class WhalesController < ApplicationController
  before_action :set_whale, only: [:show, :edit, :update, :destroy]

  def index
    @whales = Whale.all
  end

  def report
    ReportWorker.perform_async
    render text: "REQUEST ADDED!"
    # redirect_to whales_path
  end

  # GET /whales/1
  def show
    RideJob.perform_now
  end

  # GET /whales/new
  def new
    @whale = Whale.new
  end

  # GET /whales/1/edit
  def edit
  end

  # POST /whales
  def create
    @whale = Whale.new(whale_params)

    if @whale.save
      redirect_to @whale, notice: 'Whale was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /whales/1
  def update
    if @whale.update(whale_params)
      redirect_to @whale, notice: 'Whale was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /whales/1
  def destroy
    @whale.destroy
    redirect_to whales_url, notice: 'Whale was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_whale
      @whale = Whale.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def whale_params
      params.require(:whale).permit(:name, :weight)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>WhaleReviewSite</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <nav>
      <ul>
        <% if user_signed_in? %>
          <li><%= link_to 'Sign Out', '#' %></li>
        <% else %>
          <li><%= link_to "Sign Up", new_user_registration_path %></li>
        <% end %>
      </ul>
    </nav>

    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    
    <%= yield %>
  </body>
</html>

app/views/whales/_form.html.erb
<%= form_for(whale) do |f| %>
  <% if whale.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(whale.errors.count, "error") %> prohibited this whale from being saved:</h2>

      <ul>
      <% whale.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/whales/edit.html.erb
<h1>Editing Whale</h1>

<%= render 'form', whale: @whale %>

<%= link_to 'Show', @whale %> |
<%= link_to 'Back', whales_path %>

app/views/whales/index.html.erb
<h1>Whales</h1>


    <% @whales.each do |whale| %>
      <ul>
        <li><%= whale.name %></li>
        <li><%= link_to 'Show', whale %></li>
      </ul>
    <% end %>

<br>

<%= button_to 'Create Report', report_path, method: :post%>

app/views/whales/new.html.erb
<h1>New Whale</h1>

<%= render 'form', whale: @whale %>

<%= link_to 'Back', whales_path %>

app/views/whales/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @whale.name %>
</p>

<%= link_to 'Edit', edit_whale_path(@whale) %> |
<%= link_to 'Back', whales_path %>